List<String> fishingGearList = [
  "Gill Net (pante)",
  "Spear Gun (pana)",
  "Hook & Line (kawil)",
  "Fish Trap (bubo)",
  "Fish Corral (baklad)",
  "Lift Net (pantaas)",
  "Beach Seine (pukot)",
  "Scissors Net (salap)",
  "Crab Lift Net (bintol)",
  "Motorized Push Net (suro)",
  "Ring Net (basnig)",
  "Cover Pot (saklob)",
  "Fish Shelter (paksol)",
  "Drive-in Net (sakag/paksol)",
  "Bamboo Fish Trap (tukil)",
  "Scoop Net (sigpaw)",
  "Fish Spear (salapang)",
  "Rake (balukay)",
  "Cast Net (dala)",
  "Fish Pot (patanga)"
];
