List<String> speciesList = [
  "Flag-tailed glass perchlet (ning-ning)",
  "Midas cichlid (red tilapia)",
  "Climbing perch (martiniko)",
  "Giant mottled eel (igat)",
  "Manila sea catfish (kanduli)",
  "Eendracht Land silverside (guno)",
  "Giant trevally (maliputo)",
  "Big-eye trevally (muslo)",
  "Crucian carp (karpita)",
  "Striped snakehead (dalag)",
  "Milkfish (bangus)",
  "Philippine catfish (hito)",
  "Bighead catfish (hito)",
  "Common carp (karpa)",
  "Pipefish (kambabalo)",
  "Tenpounder (Kanoping)",
  "Half-barred cardinal (dangat)",
  "Whipfin silver-biddy (balabatuhan)",
  "Snakehead gudgeon (baculi)",
  "Celebes goby (biyang bato)",
  "Tank goby (biyang puti)",
  "Bighead carp (bighead)",
  "Quoy's garfish (siliw)",
  "Barramundi (apahap)",
  "Silver perch (ayungin)",
  "Mangrove red snapper (also)",
  "Malabar blood snapper (maya-maya)",
  "Indo-Pacific tarpon (buan-buan)",
  "Sharptail goby (biya)",
  "Gossamer blenny (isdang mamay)",
  "Nile tilapia (tilapia)",
  "Striped catfish (pangasius)",
  "Jaguar guapote (dugong)",
  "Greenback mullet (Banak)",
  "Sleepy goby (biya)",
  "Vermiculated sailfin catfish (janitor fish)",
  "Freshwater sardine (tawilis)",
  "Blackchin tilapia (tilapiang arroyo)",
  "Spotted scat (kitang)",
  "Jarbua terapon (bagaong)",
  "Banded archerfish (kataba)",
  "Three spot gourami (gurami)",
  "Humpbacked cardinalfish (muang)",
  "Feathered river-garfish (siliw)"
];
